/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorksheetsIdRouteImport } from './routes/worksheets.$id'
import { Route as WorksheetsIdMcqRouteImport } from './routes/worksheets_.$id.mcq'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksheetsIdRoute = WorksheetsIdRouteImport.update({
  id: '/worksheets/$id',
  path: '/worksheets/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksheetsIdMcqRoute = WorksheetsIdMcqRouteImport.update({
  id: '/worksheets_/$id/mcq',
  path: '/worksheets/$id/mcq',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/worksheets/$id': typeof WorksheetsIdRoute
  '/worksheets/$id/mcq': typeof WorksheetsIdMcqRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/worksheets/$id': typeof WorksheetsIdRoute
  '/worksheets/$id/mcq': typeof WorksheetsIdMcqRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/worksheets/$id': typeof WorksheetsIdRoute
  '/worksheets_/$id/mcq': typeof WorksheetsIdMcqRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/worksheets/$id' | '/worksheets/$id/mcq'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/worksheets/$id' | '/worksheets/$id/mcq'
  id: '__root__' | '/' | '/worksheets/$id' | '/worksheets_/$id/mcq'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorksheetsIdRoute: typeof WorksheetsIdRoute
  WorksheetsIdMcqRoute: typeof WorksheetsIdMcqRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worksheets/$id': {
      id: '/worksheets/$id'
      path: '/worksheets/$id'
      fullPath: '/worksheets/$id'
      preLoaderRoute: typeof WorksheetsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worksheets_/$id/mcq': {
      id: '/worksheets_/$id/mcq'
      path: '/worksheets/$id/mcq'
      fullPath: '/worksheets/$id/mcq'
      preLoaderRoute: typeof WorksheetsIdMcqRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorksheetsIdRoute: WorksheetsIdRoute,
  WorksheetsIdMcqRoute: WorksheetsIdMcqRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
